version: '3.1'
volumes:
  pgvol:
services:
  db:
    build: postgres
    image: local/postgres-weather
    restart: always
    volumes: 
      - "pgvol:/var/lib/postgresql/data"
  dloader:
    build: icon-downloader
    image: local/weather-icon-downloader
    restart: always
  rest:
    command: ["gunicorn","-b","0.0.0.0:6000","--access-logfile","-","--error-logfile","-","webapp:application"]
    logging: 
      driver: "json-file"
      options: 
        mode: "non-blocking"
        max-size: "500m"
        max-file: "20"
    environment: 
      - WEB_CONCURRENCY=4
    build: rest-service
    image: local/rest
    restart: always
    ports:
      - "80:6000"